/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_labyrinthe;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author bapti
 */
public class FenetreAccueil extends javax.swing.JFrame {

    private final Image background;
    private int nbJoueurs;

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {
        CustomInitComponents();
        this.background = new ImageIcon("./accueil.png").getImage();
    }

    private void CustomInitComponents() {

        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // on créé un fond noir
        getContentPane().add(fond_noir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, getWidth(), getHeight()));

        panel_noms.setVisible(false);

        panel_erreur.setVisible(false);

        panel_solo.setVisible(false);

        panel_multiplayer.setVisible(false);

        pack();
        setVisible(true);
    }

    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        g.drawImage(background, 0, 0, getWidth(), getHeight(), this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_home = new javax.swing.JButton();
        panel_multiplayer = new javax.swing.JPanel();
        panel_btn = new javax.swing.JPanel();
        btn_2j = new javax.swing.JButton();
        btn_4j = new javax.swing.JButton();
        btn_3j = new javax.swing.JButton();
        panel_noms = new javax.swing.JPanel();
        panel_j1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomJoueur1 = new javax.swing.JTextField();
        panel_j4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nomJoueur4 = new javax.swing.JTextField();
        panel_j3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomJoueur3 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panel_erreur = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_j2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomJoueur2 = new javax.swing.JTextField();
        panel_solo = new javax.swing.JPanel();
        btn_solovs = new javax.swing.JButton();
        btn_solovsIA = new javax.swing.JButton();
        panel_modes = new javax.swing.JPanel();
        btn_solo = new javax.swing.JButton();
        btn_multiplayer = new javax.swing.JButton();
        img_labyrinthe = new javax.swing.JLabel();
        fond_noir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/bouton-daccueil-pour-linterface.png"))); // NOI18N
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 70, 70));

        panel_multiplayer.setOpaque(false);
        panel_multiplayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_btn.setBackground(new java.awt.Color(0, 0, 0));
        panel_btn.setOpaque(false);
        panel_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_2j.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_2j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/button2players.png"))); // NOI18N
        btn_2j.setToolTipText("");
        btn_2j.setActionCommand("Start");
        btn_2j.setDoubleBuffered(true);
        btn_2j.setFocusCycleRoot(true);
        btn_2j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2jActionPerformed(evt);
            }
        });
        panel_btn.add(btn_2j, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 80));

        btn_4j.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_4j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/button4players.png"))); // NOI18N
        btn_4j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4jActionPerformed(evt);
            }
        });
        panel_btn.add(btn_4j, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 80));

        btn_3j.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_3j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/button3players.png"))); // NOI18N
        btn_3j.setDefaultCapable(false);
        btn_3j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3jActionPerformed(evt);
            }
        });
        panel_btn.add(btn_3j, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 300, 80));

        panel_multiplayer.add(panel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 340, 290));

        getContentPane().add(panel_multiplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 420, 460));

        panel_noms.setOpaque(false);
        panel_noms.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_j1.setOpaque(false);
        panel_j1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Joueur 1 :");
        panel_j1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        nomJoueur1.setToolTipText("");
        nomJoueur1.setPreferredSize(new java.awt.Dimension(100, 22));
        nomJoueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur1ActionPerformed(evt);
            }
        });
        panel_j1.add(nomJoueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        panel_noms.add(panel_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 50));

        panel_j4.setOpaque(false);
        panel_j4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Joueur 4 : ");
        panel_j4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        nomJoueur4.setToolTipText("");
        nomJoueur4.setPreferredSize(new java.awt.Dimension(100, 22));
        nomJoueur4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur4ActionPerformed(evt);
            }
        });
        panel_j4.add(nomJoueur4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        panel_noms.add(panel_j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 60));

        panel_j3.setOpaque(false);
        panel_j3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Joueur 3 :");
        panel_j3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        nomJoueur3.setToolTipText("");
        nomJoueur3.setPreferredSize(new java.awt.Dimension(100, 22));
        nomJoueur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJoueur3ActionPerformed(evt);
            }
        });
        panel_j3.add(nomJoueur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        panel_noms.add(panel_j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 50));

        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/Play.png"))); // NOI18N
        btn_start.setToolTipText("");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panel_noms.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 300, 80));

        panel_erreur.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Veuillez entrer tous les noms. ");
        panel_erreur.add(jLabel5);

        panel_noms.add(panel_erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 40));

        panel_j2.setOpaque(false);
        panel_j2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Joueur 2 :");
        panel_j2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        panel_j2.add(nomJoueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 30));

        panel_noms.add(panel_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 220, 50));

        getContentPane().add(panel_noms, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 380, 480));

        panel_solo.setOpaque(false);
        panel_solo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_solovs.setText("Contre-la-montre");
        btn_solovs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solovsActionPerformed(evt);
            }
        });
        panel_solo.add(btn_solovs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 40));

        btn_solovsIA.setText("Solo vs IA");
        btn_solovsIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solovsIAActionPerformed(evt);
            }
        });
        panel_solo.add(btn_solovsIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 40));

        getContentPane().add(panel_solo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 280, 140));

        panel_modes.setOpaque(false);
        panel_modes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_solo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/Singleplayer.png"))); // NOI18N
        btn_solo.setToolTipText("");
        btn_solo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soloActionPerformed(evt);
            }
        });
        panel_modes.add(btn_solo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        btn_multiplayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/Multiplayer.png"))); // NOI18N
        btn_multiplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplayerActionPerformed(evt);
            }
        });
        panel_modes.add(btn_multiplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 300, 80));

        getContentPane().add(panel_modes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 610, 120));

        img_labyrinthe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/accueil.png"))); // NOI18N
        getContentPane().add(img_labyrinthe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 910, 640));

        fond_noir.setBackground(new java.awt.Color(0, 51, 51));
        fond_noir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projet_labyrinthe/fond_noir.png"))); // NOI18N
        getContentPane().add(fond_noir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-620, 120, 1940, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_4jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4jActionPerformed
        clickBouton(true, 4);
    }//GEN-LAST:event_btn_4jActionPerformed

    private void btn_3jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3jActionPerformed
        clickBouton(true, 3);
    }//GEN-LAST:event_btn_3jActionPerformed

    private void btn_2jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2jActionPerformed
        clickBouton(true, 2);
    }//GEN-LAST:event_btn_2jActionPerformed

    private void nomJoueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJoueur1ActionPerformed
    }//GEN-LAST:event_nomJoueur1ActionPerformed

    private void nomJoueur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJoueur3ActionPerformed
    }//GEN-LAST:event_nomJoueur3ActionPerformed

    private void nomJoueur4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJoueur4ActionPerformed
    }//GEN-LAST:event_nomJoueur4ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

        ArrayList<Joueur> listeJoueur = new ArrayList<Joueur>();
        String nomJ1 = nomJoueur1.getText();
        String nomJ2 = nomJoueur2.getText();
        String nomJ3 = nomJoueur3.getText();
        String nomJ4 = nomJoueur4.getText();

        Joueur player1 = new Joueur(nomJ1, "skin1");
        Joueur player2 = new Joueur(nomJ2, "skin2");
        Joueur player3 = new Joueur(nomJ3, "skin3");
        Joueur player4 = new Joueur(nomJ4, "skin4");

        switch (nbJoueurs) {

            case 1:
                panel_noms.add(panel_erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 40));
                if (nomJoueur1.getText().isEmpty()) {
                    panel_erreur.setVisible(true);
                }
                else{
                    listeJoueur.add(player1);
                    Partie partie = new Partie(listeJoueur);
                    partie.startWindow();
                    this.dispose();
                }
            case 2:
                panel_noms.add(panel_erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 40));
                if (nomJoueur1.getText().isEmpty() || nomJoueur2.getText().isEmpty()) {
                    panel_erreur.setVisible(true);
                } else {
                    listeJoueur.add(player1);
                    listeJoueur.add(player2);
                    Partie partie = new Partie(listeJoueur);
                    partie.startWindow();
                    this.dispose();
                }
                break;
            case 3:
                panel_noms.add(panel_erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 40));
                if (nomJoueur1.getText().isEmpty() || nomJoueur2.getText().isEmpty() || nomJoueur3.getText().isEmpty()) {
                    panel_erreur.setVisible(true);
                } else {
                    listeJoueur.add(player1);
                    listeJoueur.add(player2);
                    listeJoueur.add(player3);
                    Partie partie = new Partie(listeJoueur);
                    partie.startWindow();
                    this.dispose();
                }
                break;
            case 4:
                panel_noms.add(panel_erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 40));
                if (nomJoueur1.getText().isEmpty() || nomJoueur2.getText().isEmpty() || nomJoueur3.getText().isEmpty() || nomJoueur4.getText().isEmpty()) {
                    panel_erreur.setVisible(true);
                } else {
                    listeJoueur.add(player1);
                    listeJoueur.add(player2);
                    listeJoueur.add(player3);
                    listeJoueur.add(player4);
                    Partie partie = new Partie(listeJoueur);
                    partie.startWindow();
                    this.dispose();
                }
                break;
        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_mode() {
        img_labyrinthe.setVisible(false);
        panel_modes.setVisible(false);
    }

    private void btn_soloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soloActionPerformed
        btn_mode();
        panel_solo.setVisible(true);
    }//GEN-LAST:event_btn_soloActionPerformed

    private void btn_multiplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplayerActionPerformed
        btn_mode();
        panel_multiplayer.setVisible(true);
    }//GEN-LAST:event_btn_multiplayerActionPerformed

    private void btn_solovsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solovsActionPerformed
        clickBouton(true, 1);
    }//GEN-LAST:event_btn_solovsActionPerformed

    private void btn_solovsIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solovsIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solovsIAActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        home();
        
    }//GEN-LAST:event_btn_homeActionPerformed

    private void home(){
        img_labyrinthe.setVisible(true);
        
        panel_noms.setVisible(false);

        panel_erreur.setVisible(false);

        panel_solo.setVisible(false);

        panel_multiplayer.setVisible(false);
        
        panel_modes.setVisible(true);
        
        clickBouton(false, 5);

        
    }
    
    private void clickBouton(boolean cliqué, int nbJoueurs) {

        this.nbJoueurs = nbJoueurs;
        panel_btn.setVisible(!cliqué);
        panel_noms.setVisible(cliqué);
        panel_j1.setVisible(cliqué);
        panel_j2.setVisible(false);
        panel_j3.setVisible(false);
        panel_j4.setVisible(false);

        switch (nbJoueurs) {
            case 2:
                panel_j2.setVisible(cliqué);
                panel_solo.setVisible(false);
                break;
            case 3:
                panel_j2.setVisible(cliqué);
                panel_j3.setVisible(cliqué);
                break;
            case 4:
                panel_j2.setVisible(cliqué);
                panel_j3.setVisible(cliqué);
                panel_j4.setVisible(cliqué);
                break;
            default:
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            FenetreAccueil fenetre = new FenetreAccueil();
            fenetre.setExtendedState(JFrame.MAXIMIZED_BOTH); // Ouvrir en plein écran
            fenetre.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_2j;
    private javax.swing.JButton btn_3j;
    private javax.swing.JButton btn_4j;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_multiplayer;
    private javax.swing.JButton btn_solo;
    private javax.swing.JButton btn_solovs;
    private javax.swing.JButton btn_solovsIA;
    private javax.swing.JButton btn_start;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fond_noir;
    private javax.swing.JLabel img_labyrinthe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomJoueur1;
    private javax.swing.JTextField nomJoueur2;
    private javax.swing.JTextField nomJoueur3;
    private javax.swing.JTextField nomJoueur4;
    private javax.swing.JPanel panel_btn;
    private javax.swing.JPanel panel_erreur;
    private javax.swing.JPanel panel_j1;
    private javax.swing.JPanel panel_j2;
    private javax.swing.JPanel panel_j3;
    private javax.swing.JPanel panel_j4;
    private javax.swing.JPanel panel_modes;
    private javax.swing.JPanel panel_multiplayer;
    private javax.swing.JPanel panel_noms;
    private javax.swing.JPanel panel_solo;
    // End of variables declaration//GEN-END:variables
}
