/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_labyrinthe;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/**
 *
 * @author Ody
 */
public class FenetreVictoire extends javax.swing.JFrame {

     ArrayList<Joueur> podium;
    
    /**
     * Creates new form FenetreVictoire
     */
    public FenetreVictoire(ArrayList<Joueur> podium) {
        this.podium = podium;
        this.setLocationRelativeTo(null);
        
        
         
        
        switch(podium.size()){
            case 1->{
                System.out.println("Première place pour "+podium.get(0).name);
                
            }
            case 2->{
                System.out.println("Première place pour "+podium.get(0).name);
                System.out.println("Deuxieme place pour "+podium.get(1).name);
            }
            case 3->{
                System.out.println("Première place pour "+podium.get(0).name);
                System.out.println("Deuxieme place pour "+podium.get(1).name);
                System.out.println("Troisième place pour "+podium.get(2).name);
            }
            case 4->{
                System.out.println("Première place pour "+podium.get(0).name);
                System.out.println("Deuxieme place pour "+podium.get(1).name);
                System.out.println("Troisième place pour "+podium.get(2).name);
                System.out.println("Dernière place pour "+podium.get(3).name);
            }
        }
        
        initComponents();
        this.setVisible(true);
    }

   

    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Podium = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labyrinthe : Victoire");
        setPreferredSize(new java.awt.Dimension(1020, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Podium.setPreferredSize(new java.awt.Dimension(1020, 750));
        Podium.setLayout(new java.awt.GridLayout(1, 1));

        Podium.add(new UIWin());

        getContentPane().add(Podium, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Podium;
    // End of variables declaration//GEN-END:variables
}
